### ISSUE TITLE
Lightning-SDK  vs  Lightning-SDK-blueprint

### ISSUE THREAD

**Issue by wilberhdez** [WebPlatformForEmbedded/Lightning-SDK#1]
I had to follow the "Lightning-SDK-blueprint" approach and it worked for me -
https://github.com/WebPlatformForEmbedded/Lightning-SDK-blueprint

Anyone know the difference between -
Lightning-SDK-blueprint
Lightning-SDK

**Comment by nikola-nikov** [comment]
Lightning-SDK-blueprint is stand alone app that uses Lightning-SDK

**Comment by woutermeek** [comment]
@wilberhdez  Does this answer your question? If so can we close the ticket?

**Comment by g-zachar** [comment]
Closing this issue for now, please reopen if still relevant.
