### ISSUE TITLE
Error on using Player from Lightning-SDK

### ISSUE THREAD

**Issue by Sumitha-95** [WebPlatformForEmbedded/Lightning-SDK#12]
Hi,
I tried to use the Player component from Lightning-SDK.But I got the following error on running the same.

Player.js:168 Uncaught (in promise) TypeError:
    Cannot read property 'link' of undefined
    at StateMachineRouter.getMediaplayerSettings (Player.js:168)
    at StateMachineRouter.updateSettings (Mediaplayer.js:156)
    at StateMachineRouter._handleFocusSettings (Ui.js:139)
    at StateMachineRouter.updateFocusSettings (lightning-web.js:16617)
    at StateMachineRouter.__updateFocus (lightning-web.js:16534)
    at StateMachineRouter.updateFocusPath (lightning-web.js:16527)
    at StateMachineRouter.__onStateChange (lightning-web.js:10660)
    at StateMachineRouter._setState (lightning-web.js:10074)
    at StateMachineRouter._focus (PlayerButton.js:42)
    at StateMachineRouter.__updateFocusRec (lightning-web.js:16584)

Can you help me with this.

**Comment by g-zachar** [comment]
Hey, can yo provide more details about your problem?

**Comment by Sumitha-95** [comment]
@g-zachar Adding my App.js below.


`export default class App extends ux.App {
    static getFonts() {
      return [];
    }

    static _template() {
      return {
        Player: {
          type: ux.tools.player.Player
        }

        // Text: {text: {text: "hello world"}}
      };
    }

    _init() {
      const item = { title:'video', stream: { link:'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4' }}
      let items = [];
      items.push(item);
      const playlist = { item,items  }
      this.tag('Player').fire('play', playlist)
    }

  }
`

**Comment by g-zachar** [comment]
Looks like there are at least several issues with the player that will hopefully be addressed in the future. For now, here's working example:

```javascript
export default class App extends ux.App {
    static getFonts() {
        return [];
    }
    
    static _template() {
      return {
        Player: {
          type: ux.tools.player.Player
        }
      };
    }

    _getFocused() {
        return this.init ? this.tag('Player') : this
    }

    _init() {
        this.init = false;
        const item = { title:'video', stream: { link:'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4' }}
        const items = [item];
        this.tag('Player').play({item, items})
        this.init = true;
    }
}
```
