### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by nikola-nikov** [WebPlatformForEmbedded/Lightning-SDK#15]
Hi guys,
I'm looking for a way to reuse our Lightening app in a browser, making it mouse accessible. Can you give me a hint. Is it possible to add on click event handlers to the UI elements and if so, how to achieve it?

**Comment by g-zachar** [comment]
Hi @nikola-nikov 

Unfortunately, currently Lightning does not support click events. You can request feature [here](https://github.com/WebPlatformForEmbedded/Lightning/issues).
