### ISSUE TITLE
Support for Windows commands in ./scripts/release-web.js

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-SDK#21]
Example issue:
https://stackoverflow.com/questions/17607612/equivalent-of-rm-and-mv-in-windows-cmd

**Comment by wouterlucas** [comment]
These are fixed in the #next branch, we hope to push that to master soon. Though I havent tried it on Windows myself, the usage of shelljs should solve that in the build scripts on the next branch.

**Comment by MattiaPontonioKineton** [comment]
https://github.com/shelljs/shelljs

**Comment by michielvandergeest** [comment]
Closing issue, since next branch has now been merged to master.

Also the release and upload functionality has been moved from the SDK to the CLI (https://github.com/WebPlatformForEmbedded/Lightning-CLI)
