### ISSUE TITLE
hello world App not working in Edge

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-SDK#23]
Following the readme and Try to lunch a Hello Word App it shows well in Chrome but **white screen** in Edge, without errors in console.
### index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
</head>
<body>
    <script type="module">
        import DevLauncher from "./node_modules/wpe-lightning-sdk/DevLauncher.js";
        import App from "./src/App.js";
    
        const launcher = new DevLauncher();
        launcher.launch(App, {debug: true}, {useInspector: false})
    </script>
</body>
</html>
```
### App.js
```
export default class MyApp extends ux.App {
    static _template() {
        return {
            Text: {text: {text: "hello world"}}
        }
    }
}
```
### Screenshot from Chrome
![2020-01-08 (2)](https://user-images.githubusercontent.com/58947115/72001934-bee50100-3246-11ea-8715-46f49de7a05d.png)
### Screenshot from Edge 44.18362.1.0
![2020-01-08 (1)](https://user-images.githubusercontent.com/58947115/72001944-c1475b00-3246-11ea-8f04-4e6c72fe658c.png)

**Comment by wouterlucas** [comment]
Edge is currently not one of our targets, though theoretically this could work. Edge does support WebGL and should support fairly recent ES6 features. 

Just for my understanding are you actually targetting deployment on an edge browser or is this encountered during local testing/development?

**Comment by MattiaPontonioKineton** [comment]
Hello @wouterlucas,

thanks from your response. 
Actually I'm not targeting Edge in deployment but in my experience the "severity" of Microsoft's browsers should be a good help for spotting issues in development.

Looking to
https://github.com/WebPlatformForEmbedded/Lightning/pull/97
for test if solve some issues.

Best regards
Mattia

**Comment by michielvandergeest** [comment]
Es5-support is in the works. An Es5 version could possibly be used to run in Edge.
