### ISSUE TITLE
Broken link in DOC

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-SDK#29]
Hello,
in this page:
https://webplatformforembedded.github.io/Lightning-SDK/#/plugins/settings
this link is broken
https://webplatformforembedded.github.io/Lightning/docs/gettingStarted/configuration#stage-configuration-options
Lightning doc is changed from someday starting from now.
Can You please extend the DOC including the scope of the `stage` object?
Regards
Mattia

**Comment by michielvandergeest** [comment]
Fixed in new release.
