### ISSUE TITLE
Storage requires Launching app first

### ISSUE THREAD

**Issue by chiefcll** [WebPlatformForEmbedded/Lightning-SDK#38]
I have some query params that I save in localStorage required to start the app. I can't Launch the app without them, and I can't use Storage without first calling Launch. These need to be decoupled.

**Comment by michielvandergeest** [comment]
The Storage plugin of the SDK is intended for use only _within_ the App context itself. The plugin actually even namespaces the storage keys with the App ID to prevent collisions between Apps.
For that reason the Storage plugin is only initialised during App launch (and not before).

Your use case seems to be a bit different from the standard SDK / Metro app store approach, so I’m assuming you’re initialising your App manually as well? In that case, you could simply read those saved query params directly from localStorage yourself. In the end the SDK's Storage plugin is just a facade for the standard localStorage web API (with a fallback to cookies, when not available).

Hope that helps. Feel free to follow up with more details about your specific situation!

**Comment by chiefcll** [comment]
This is fine - I refactored my code to use localCookie from the SDK
