### ISSUE TITLE
Media Player example

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-SDK#39]
Hello,

there is some open source working example of this: 
https://webplatformforembedded.github.io/Lightning-SDK/#/plugins/mediaplayer
?

Best regards
Mattia

**Comment by Thomvl** [comment]
Hi,
You can find a code snippet here:
https://webplatformforembedded.github.io/Lightning/docs/player/player

KR.
Thom
