### ISSUE TITLE
Update Settings

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-SDK#40]
Referring to this:
https://webplatformforembedded.github.io/Lightning-SDK/#/plugins/mediaplayer?id=update-settings
which is the method where to place:
`this.tag('MediaPlayer').updateSettings({consumer: this})`
?
Is a https://webplatformforembedded.github.io/Lightning/docs/components/overview#component-events ?

**Comment by michielvandergeest** [comment]
I would suggest putting this in `_init()` or `_firstActive`.
