### ISSUE TITLE
Navigating in Lightning.Component

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-SDK#41]
https://github.com/WebPlatformForEmbedded/Lightning-SDK/blob/bdd0cc540f43289323ed17b19788fe9d9bd4650c/src/Lightning/index.js#L1

In VS Code with `CTRL + click` You can navigate through classes and imports.
This code prevents to inspect `Lightning.Component` that can be useful for understanding what methods are available.
Where is `lng`? Who puts it in `windows`?

**Comment by michielvandergeest** [comment]
'window.lng` refers to Lightning.

The Lightning library attaches itself to the window object when it's loaded (https://github.com/WebPlatformForEmbedded/Lightning/blob/master/src/lightning.mjs#L113-L115).

The Lightning plugin in the SDK is merely a proxy to this global window variable.

**Comment by MattiaPontonioKineton** [comment]
@michielvandergeest,
thanks. I suggest importing even then proxying.
It should be safer and provides a reference.
