### ISSUE TITLE
Specifics for videoUrl - mediaplayer open

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-SDK#42]
Referring this:
https://webplatformforembedded.github.io/Lightning-SDK/#/plugins/mediaplayer?id=open
there are some specifics for `videoUrl`?
Does it have to serve a file? What extensions? What kind of resource?

**Comment by michielvandergeest** [comment]
Which files can be played depends on the video capabilities of the device your Lightning App is running on. Your safest bet in general are mp4 files.

**Comment by MattiaPontonioKineton** [comment]
I suggest referencing this:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source
