### ISSUE TITLE
[ERROR] Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-SDK#43]
From console:

  | canplay | @ | index.js:430
-- | -- | -- | --
  | fire | @ | lightning.es5.js:11719
  | handler | @ | index.js:92

In my src I've implemented the mthod playPause() only in one method, something like this:
```
import { Lightning, MediaPlayer } from 'wpe-lightning-sdk'
import PlayerControls from './PlayerControls'
import PlayerProgress from './PlayerProgress'
export default class Player extends Lightning.Component {
  static _template() {
    return {
      Controls: {
        x: 99,
        y: 0,
        type: PlayerControls // some custom class for Player Controls
      },
      Progress: {
        x: 99,
        y: 970,
        type: PlayerProgress // some custom class for Player Progress bar
      },
      MediaPlayer: {
        type: MediaPlayer
      }
    }
  }
  _firstActive() {
    this.tag('MediaPlayer').updateSettings({
      consumer: this
    })
    this.tag('MediaPlayer').open('http://techslides.com/demos/sample-videos/small.mp4')
    this._setState('Controls')
  }
  $playPause() {
    this.tag('MediaPlayer').playPause()
  }
  $reload() {
    this.tag('MediaPlayer').reload()
    this.tag('MediaPlayer').open('http://techslides.com/demos/sample-videos/small.mp4')
  }
  static _states() {
    return [
      class Controls extends this {
        _getFocused() {
          return this.tag('Controls')
        }
      }
    ]
  }
}
```
Fired by an Enter handler so I suppose that the user had interact with the document.
```
import PlayerControl from './PlayerControl'
export default class PlayPause extends PlayerControl {
  static _template() {
    return {
      text: {
        text: 'Play Pause'
      }
    }
  }
  _handleEnter() {
    this.fireAncestors('$playPause')
  }
}
```

So seems that the error comes from the library. Is any way to solve it in my code with some practies?
## Additional info

- The error is present ONLY if I refresh the browser.
- The error is not present if the browser is launched by the automatic launch by VS code using lng dev by Lightning CLI
- If of course I use lng dev, the video Plays 1 time at the beginning and I do not need this behavioru, I need to play just with my controls from the user

**Comment by Thomvl** [comment]
This error is a Browser Security Feature, mainly to prevent popups for playing audio/video.
To solve this you can whitelist your local host to allow immediate playback, or make sure that before the play you press some keys to let your browser know its getting user input

**Comment by MattiaPontonioKineton** [comment]
@Thomvl thanks!
So the Play handler has to be NOT the first interaction but the second at least.
So no possibilities to set the focus immediately on the PLAY button when the app starts. 
It's correct?
I need for example to navigate in some way to the play button and then press it.

**Comment by Thomvl** [comment]
It depends on the platform you are targeting with your app. As this is a browser feature it depends on the browser you are going to run the app in. WPE allows you to instantly play a video without any user input. 

As for your second question, an 'enter' or 'ok' press also accounts for user input, so you could move the focus to the play button and let the user press it.
