### ISSUE TITLE
Insufficient media player documentation

### ISSUE THREAD

**Issue by nikola-nikov** [WebPlatformForEmbedded/Lightning-SDK#5]
I'm looking for a Player implementation with progressbar and media buttons, that can be manipulated from the remote. I think that Player example is insufficient. It will be great if there is working Player implementation in one of the Github projects.

**Comment by v42** [comment]
@nikola-nikov the SDK has a working example:

https://github.com/WebPlatformForEmbedded/Lightning-SDK/blob/master/js/src/tools/player/Player.js

you can use it like this:
```js
 // title: title of your video
// link: url to your video
const item = { title, stream: { link }}

//item: current video, items is an array containing your video
const playlist = { item, items }

//and then you send it to your player
this.tag('Player').fire('play', playlist)
```

**Comment by woutermeek** [comment]
@nikola-nikov We have documentation on the player online now:

https://webplatformforembedded.github.io/Lightning/docs/player/player

**Comment by g-zachar** [comment]
Closing this issue for now, please reopen if still relevant.
