### ISSUE TITLE
WebGL feature toggle is ignored and WebGL is always forced

### ISSUE THREAD

**Issue by MLangendijk** [WebPlatformForEmbedded/Lightning-SDK#6]
One of the set-top-boxes we have does not support WebGL. The Wuf.js library however forces this, and does not do anything with the `canvas2d` feature toggle as defined in the Lightning documentation (https://webplatformforembedded.github.io/Lightning/docs/gettingStarted/configuration). Are there plans to also support non-WebGL rendering, or will this SDK always require WebGL?

**Comment by oscaruitenbroek** [comment]
@MLangendijk closing ticket, we solved it via Skype.

**Comment by erikhaandrikman** [comment]
Nice that it’s solved! I think it’s wise to share some details here for people who stumble upon the same issue in the future
