### ISSUE TITLE
Impossible to render MediaPlayer above any UI component

### ISSUE THREAD

**Issue by Serg-de-Adelantado** [WebPlatformForEmbedded/Lightning-SDK#60]
Some OTT apps has previews over thumbnail: when user moves focus to a tile, it's possible to see a sneak peek of a video. Seems like it's not possible to implement this feature with Lightning SDK since MediaPlayer is not able to render over UI. Here is a code example showing this issue:
```js
import { Lightning, Utils, MediaPlayer } from 'wpe-lightning-sdk'

export default class App extends Lightning.Component {
  static _template() {
    return {
      Background: {
        rect: true,
        w: 1920,
        h: 1080,
        colorTop: 0xff0f2212,
        colorBottom: 0xff000000
      },
      MediaPlayer: {
        type: MediaPlayer
      }
    }
  }

  _init() {
    const video = this.tag('MediaPlayer')
    video.loop = true
    video.muted = true
    video.open(Utils.asset('background-loop-1080p.mp4'))
  }
}
```
In this example video should be rendered above the `Background` node however it's rendered on a very bottom of render tree.

**Comment by mattiapontonio** [comment]
https://github.com/WebPlatformForEmbedded/Lightning/issues/95

**Comment by Serg-de-Adelantado** [comment]
@mattiapontonio you referring to a ticket that describes rendering of a video DOM element. My issue is related to Lightning render tree. As you may see in sources there is a RTT for `video` DOM element, i.e. video could be rendered in "off-sceen" mode: https://github.com/WebPlatformForEmbedded/Lightning-SDK/blob/master/src/MediaPlayer/index.js#L130. However, for some reason this texture could not be rendered on top of any other component.

**Comment by Serg-de-Adelantado** [comment]
Seems like I was missing the `textureMode` parameter:
https://github.com/WebPlatformForEmbedded/Lightning-SDK/blob/15a54a612df9b7c21aa8f77ad114462d29761f54/src/MediaPlayer/index.js#L33

**Comment by mattiapontonio** [comment]
I was thinking that It was some "Legacy limitation". I Will try the solucion as soon I can. Thanks.
