### ISSUE TITLE
Is settings.json extensible?

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning-SDK#61]
Can I add my custom settings like `colors`, `contants`, etc?

**Comment by michielvandergeest** [comment]
Technically you can add them to `settings.json`, but keep in mind that this file will **not** be uploaded to the Metrological App store (https://webplatformforembedded.github.io/Lightning-SDK/#/plugins/settings). In production these settings are defined by the App store based on platform specifics.

So for this type of app specific configuration, that don't depend on environments, it's probably better to create `js` files _inside_ your `src` folder that export the config.
