### ISSUE TITLE
cp: no such file or directory 

### ISSUE THREAD

**Issue by paynetechnologies** [WebPlatformForEmbedded/Lightning-SDK#65]
Two different GitHub Tic-Tac-Toe examples both have the same issues. 

When I issue the lng serve command, I get the following messages (see below) and the Browser simply opens an "Index of" page.

Do these two apps need updating? Or is something wrong with my installation?

The Apps:
https://github.com/mlapps/lightning-getting-started-docs
https://github.com/KadeejaBai/Lightning-Tic-Tac-Toe-MinionGame

=====================

⚠️  You are using an older version of the Lightning SDK. Please consider upgrading to the latest version.  ⚠️

cp: no such file or directory: ./node_modules/wpe-lightning/dist/lightning.js
cp: no such file or directory: ./node_modules/wpe-lightning/devtools/lightning-inspect.js
cp: no such file or directory: ./node_modules/wpe-lightning-sdk/support/*
=======================

Thank you,
Howard

**Comment by michielvandergeest** [comment]
This error seems to indicate that a post-install script didn't run or that you are running an older version of Lightning.

I suggest you start by removing the `node_modules` folder and `package-lock.json` and then run `npn install` again.

This should make sure you have all the latest dependencies and hopefully solve your issue.
