### ISSUE TITLE
Utils.asset not working as expected

### ISSUE THREAD

**Issue by barnomics** [WebPlatformForEmbedded/Lightning-SDK#68]
As a consumer of Utils.asset, I expect the function to return the absolute path to an asset no matter which route of my application I'm on. 

It works if I load the application from the root, like `http://example.com/` then navigate around.

But when I navigate to a route within the app, like `http://example.com/settings/some-setting` and *refresh* the page, the Util stops working as desired and all of the images error because now the asset path is `https://example.com/settings/static/icons/image.png`

I understand that refreshing the app like this on hardware is unlikely, but it's very important to be able to do for developer speed.  

I think the culprit is this line in initUtils 
https://github.com/WebPlatformForEmbedded/Lightning-SDK/blob/2e2559c79fd3672db1399d9ec9b3857bbecccde8/src/Utils/index.js#L6

It's taking the pathname `/settings/some-setting`, appending the config path, generating the basePath `https://example.com/settings/static`

One expects it to be an absolute `https://example.com/static` no matter which route of the application I load.

**Comment by michielvandergeest** [comment]
hi @barnomics, it's possible this functionality hasn't been fully battle tested with uri-based routing (since the metro app store is always loaded from the root-domain).

Let me try to replicate your issue here. What do you have as a value for `path` in `platformSettings`?

**Comment by michielvandergeest** [comment]
Fixed in release 2.2.0

**Comment by fernando-j-afonso-alb** [comment]
I'm having a problem with local assets.

For instance, with lng create, the getFonts use Utils.asset('fonts/Roboto-Regular.ttf'). For webOS, using the ares-install, launching the app, Utils.asset returns file://com.domain.app/media/developer/apps/usr/palm/applications/com.domain.app/static/fonts/Roboto-Regular.ttf, where the real location for the static files is file:///media/developer/apps/usr/palm/applications/com.domain.app/static/fonts/Roboto-Regular.ttf

I don't know if this is a problem with my webOS or I'm doing something wrong, but as I can realize in the code, using a file://, the url is appended with window.location.origin

modelName : OLED55C7V-Z
sdkVersion : 3.9.0
firmwareVersion : 06.00.25
boardType : M16P_DVB_EU

**Comment by michielvandergeest** [comment]
@fernando-j-afonso-alb it seems like the `path` in your settings.json isn't set correctly. Could you try setting it to: `file:///media/developer/apps/usr/palm/applications/com.domain.app/static` and see if that helps?

**Comment by fernando-j-afonso-alb** [comment]
Sure.

var platformSettings = {
  "path": "file:///media/developer/apps/usr/palm/applications/com.domain.app/static",
  "log": true,
  "showVersion": true,
  "esEnv": "es5"
}

Output -> file://com.domain.app/media/developer/apps/usr/palm/applications/com.domain.app/file:///media/developer/apps/usr/palm/applications/com.domain.app/static/fonts/Roboto-Regular.ttf

**Comment by michielvandergeest** [comment]
Yeah, that doesn't look quite right ;-) .. we'll have a closer look at it

**Comment by fernando-j-afonso-alb** [comment]
Thank you. I'll do all the testing you need.

**Comment by fernando-j-afonso-alb** [comment]
> Yeah, that doesn't look quite right ;-) .. we'll have a closer look at it

Hi @michielvandergeest. Have you take a closer look at this? Thank you.
