### ISSUE TITLE
Non-recursive shaders

### ISSUE THREAD

**Issue by lewispeel** [WebPlatformForEmbedded/Lightning-SDK#77]
I'm trying to apply a rounded rectangle shader to a container but it seems to be recursively passing the shader to its children giving everything rounded corners rather than just the container. 

I can see the benefit of this approach in some use cases (like grayscale, blur etc) but sometimes this is undesirable behaviour, for example;

![rounded-rect-shader](https://user-images.githubusercontent.com/1321492/82039092-67471e00-969c-11ea-97cc-69e98d7c266f.png)

```
import { Lightning } from 'wpe-lightning-sdk'

export default class App extends Lightning.Component {
  static _template() {
    return {
      Boxes: {
        x: 760, y: 340,
        w: 400, h: 400,
        shader: {
          type: Lightning.shaders.RoundedRectangle,
          radius: 20,
        },
      },
    }
  }

  _init() {
    this._boxes = this.tag('Boxes')
    this._boxes.children = [
      { w: 200, h: 200, rect: true, color: 0xffFF0000 },
      { x: 200, w: 200, h: 200, rect: true, color: 0xff00FF00 },
      { y: 200, w: 200, h: 200, rect: true, color: 0xff0000FF },
      { x: 200, y: 200, w: 200, h: 200, rect: true, color: 0xffFFFF00 },
    ]
  }
}
```

I've tried to use `shader: null` on child components but this prevents any shader being applied (even to the parent). Is there a way to achieve the expected resulted above or is this not currently supported?

*EDIT* I'm using Lightning-CLI 1.5.0

Thanks

**Comment by lewispeel** [comment]
Closing this as I realise this should be in Lightning not, Lightning SDK - https://github.com/WebPlatformForEmbedded/Lightning/issues/180

**Comment by Thomvl** [comment]
Hi Lewis,
You are actually only missing out on one single property, called rtt (or renderToTexture).
This actually merges the whole rendertree into a new texture, and applies the shader on that new texture.

import { Lightning } from 'wpe-lightning-sdk'

export default class App extends Lightning.Component {
  static _template() {
    return {
      Boxes: {
        x: 760, y: 340,
        w: 400, h: 400,
        rtt:true,
        shader: {
          type: Lightning.shaders.RoundedRectangle,
          radius: 20,
        },
      },
    }
  }

  _init() {
    this._boxes = this.tag('Boxes')
    this._boxes.children = [
      { w: 200, h: 200, rect: true, color: 0xffFF0000 },
      { x: 200, w: 200, h: 200, rect: true, color: 0xff00FF00 },
      { y: 200, w: 200, h: 200, rect: true, color: 0xff0000FF },
      { x: 200, y: 200, w: 200, h: 200, rect: true, color: 0xffFFFF00 },
    ]
  }
}

**Comment by lewispeel** [comment]
Ahhh, amazing! Thank you, I've been trying to figure this out for hours!
